version: '3.9'
services:
  ordering.api:
    image: praisethemachinegod/mtogo-ordering
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - kafka
    networks:
      - kafka-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORTS: 9092
      KAFKA_LISTENER_NAMES: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  postgres:
    image: postgres:16.1
    container_name: OrderDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - ./Database/database-script.sql:/docker-entrypoint-initdb.d/database-script.sql
    command: -p 5433
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
